version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEEPAUTO_BASE_URL=${DEEPAUTO_BASE_URL}
      - DEEPAUTO_API_KEY=${DEEPAUTO_API_KEY}
      - DEEPAUTO_MODEL=${DEEPAUTO_MODEL}
    volumes:
      - ./server:/app
      - server_data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  client:
    build: ./nextjs
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://server:8000
    volumes:
      - ./nextjs:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - server
    command: npm run dev

volumes:
  server_data:
